toplevel: blinky
name: quartus_blinky
files: 
  - name: "pinmap.tcl"
    file_type: tclSource
    is_include_file: false
    include_path: ""
    logical_name: ""
  - name: "de1_soc_revF.sdc"
    file_type: SDC
    is_include_file: false
    include_path: ""
    logical_name: ""
  - name: "blinky.v"
    file_type: "verilogSource-2005"
    is_include_file: false
    include_path: ""
    logical_name: ""
tool_options: 
  quartus: 
    installation_path: ""
    board_device_index: ""
    family: "Cyclone\x20V"
    device: 5CSXFC6D6F31C8ES
    quartus_options: ""
    dse_options: ""