toplevel: blinky_zcu102
name: project_vivado
files: 
  - name: "blinky_zcu102.v"
    file_type: "verilogSource-2005"
    is_include_file: false
    include_path: ""
    logical_name: ""
  - name: "blinky.xdc"
    file_type: XDC
    is_include_file: false
    include_path: ""
    logical_name: ""
tool_options: 
  icarus: 
    installation_path: ""
    iverilog_options: ""
    timescale: "1ns/1ns"
