name: Upload Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build 
        id: build
        run: |
          sudo apt-get install python3-sphinx
          npm install -g vsce
          npm install
          npm run-script generate-doc
          npm run-script generate-examples
          cd node_modules/teroshdl; npm install; cd ../../
          vsce package --no-rewrite-relative-links --allow-star-activation
          now=`date +"%Y-%m-%d__%H:%M"`
          file=`ls *.vsix`
          file_ver="${now}_${file}"
          mv $file $file_ver
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: latest
          files: |
            *.vsix
